spring.datasource.url=jdbc:h2:mem:polizas;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.open-in-view=false
spring.h2.console.enabled=false
app.api-key=${API_KEY:123456}
app.core-url=${CORE_URL:http://localhost:${server.port:8080}}
